import react from "./React.png";
import ts from "./Typescript.png";
import styledComponents from "./styled-components.png";
import htmlCss from "./HTML_CSS.png";
import js from "./Javascript.png";
import c from "./C.png";
import cpp from "./C++.png";
import java from "./Java.png";
import materialUi from "./material-ui.png";
import cudac from "./CUDA.jpg";
import verilog from "./verilog.png";

export const reactImg = react;
export const tsImg = ts;
export const styledComponentsImg = styledComponents;
export const htmlCssImg = htmlCss;
export const jsImg = js;
export const cImg = c;
export const cppImg = cpp;
export const javaImg = java;
export const materialUiImg = materialUi;
export const verilogImg = verilog;
export const cudacImg = cudac;
